### ISSUE TITLE
Could not generate correct page

### ISSUE THREAD

**Issue by WilliamGong** [Solybum/hexo-deploy#1]
I add a theme by submodule, when I use the theme, it can run correctly on the local server. But After processing by the action, website html become an empty file.  No warning or error in GIthub Action log. 
Could anyone help me?

**Comment by WilliamGong** [comment]
OK I found some warnings:
'''
Generate file ...
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 129 ms
WARN  No layout: about/index.html
WARN  No layout: 2020/10/10/hello-world/index.html
WARN  No layout: archives/index.html
WARN  No layout: archives/2020/index.html
WARN  No layout: archives/2020/10/index.html
WARN  No layout: index.html
INFO  Generated: about/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2020/index.html
INFO  Generated: atom.xml
INFO  Generated: search.xml
INFO  Generated: archives/2020/10/index.html
INFO  Generated: index.html
INFO  Generated: 2020/10/10/hello-world/index.html
INFO  8 files generated in 11 ms
'''

**Comment by Solybum** [comment]
The github action actions/checkout that hexo deploy relies on doesn't checkout submodules by default
I have submitted a PR to your [hexo-blog repository](https://github.com/WilliamGong/hexo-blog/pull/1).

I will modify hexo deploy too.

**Comment by Solybum** [comment]
@WilliamGong if possible, I'd appreciate if you can report back if the change worked as I currently don't have any hexo deployments with submodules.

**Comment by WilliamGong** [comment]
It works. Thanks so much.
